#!/usr/bin/env bash
# Show or update personal ssh-remote defaults (host-agnostic onboard output).
# Usage:
#   set-defaults.sh --show
#   set-defaults.sh --host user@host.or.alias [--compose 'docker compose'] [...]
#   set-defaults.sh --clear
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=_lib.sh
source "${SCRIPT_DIR}/_lib.sh"

usage() {
  cat <<'EOF'
Usage:
  set-defaults.sh --show
  set-defaults.sh --host <user@host|ssh-config-alias> [options]
  set-defaults.sh --clear

Writes user defaults to:
  ~/.cursor/ssh-remote/defaults.yml

Options (all optional except --host on first write):
  --host <user@host|alias>
  --compose <cmd>       e.g. "docker compose" or "sudo docker-compose"
  --remote-path <path>  optional default remote project root
  --health-url <url>    optional default health URL (on remote)
  --exclude-file <path> optional default rsync exclude file

Partial updates merge into the existing defaults file (e.g. --compose only).

Precedence at runtime (high → low):
  call env / CLI host arg → project .ssh-remote.yml → this defaults.yml

Never store passwords here.
EOF
}

SHOW=0
CLEAR=0
HOST=""
COMPOSE=""
REMOTE_PATH=""
HEALTH_URL=""
EXCLUDE_FILE=""

if [[ $# -lt 1 ]]; then
  usage >&2
  exit 2
fi

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help) usage; exit 0 ;;
    --show) SHOW=1; shift ;;
    --clear) CLEAR=1; shift ;;
    --host) HOST="${2:-}"; shift 2 ;;
    --compose) COMPOSE="${2:-}"; shift 2 ;;
    --remote-path) REMOTE_PATH="${2:-}"; shift 2 ;;
    --health-url) HEALTH_URL="${2:-}"; shift 2 ;;
    --exclude-file) EXCLUDE_FILE="${2:-}"; shift 2 ;;
    *) ssh_remote_die "unknown arg: $1" ;;
  esac
done

DEFAULTS="$(ssh_remote_defaults_path)"

if [[ "${SHOW}" == "1" ]]; then
  if [[ -f "${DEFAULTS}" ]]; then
    echo "ssh-remote defaults: ${DEFAULTS}"
    cat "${DEFAULTS}"
  else
    echo "ssh-remote: no defaults file yet (${DEFAULTS})"
    echo "ssh-remote: run onboard / set-defaults.sh --host <user@host>"
    exit 1
  fi
  exit 0
fi

if [[ "${CLEAR}" == "1" ]]; then
  rm -f "${DEFAULTS}"
  echo "ssh-remote: cleared ${DEFAULTS}"
  exit 0
fi

[[ -n "${HOST}" || -f "${DEFAULTS}" ]] || ssh_remote_die "--host is required for first write (or use --show / --clear)"

# Merge with existing defaults so partial updates keep other keys
EXISTING_HOST=""
EXISTING_COMPOSE=""
EXISTING_REMOTE_PATH=""
EXISTING_HEALTH_URL=""
EXISTING_EXCLUDE=""
if [[ -f "${DEFAULTS}" ]]; then
  # shellcheck disable=SC1090
  eval "$(ssh_remote_parse_yaml "${DEFAULTS}" "EXISTING_")"
fi

HOST="${HOST:-${EXISTING_HOST}}"
COMPOSE="${COMPOSE:-${EXISTING_COMPOSE}}"
REMOTE_PATH="${REMOTE_PATH:-${EXISTING_REMOTE_PATH}}"
HEALTH_URL="${HEALTH_URL:-${EXISTING_HEALTH_URL}}"
EXCLUDE_FILE="${EXCLUDE_FILE:-${EXISTING_EXCLUDE}}"

[[ -n "${HOST}" ]] || ssh_remote_die "no host in flags or existing defaults"

mkdir -p "$(dirname "${DEFAULTS}")"
umask 077
{
  echo "# ssh-remote user defaults (no secrets). Generated by set-defaults.sh"
  echo "host: ${HOST}"
  if [[ -n "${COMPOSE}" ]]; then
    echo "compose: ${COMPOSE}"
  fi
  if [[ -n "${REMOTE_PATH}" ]]; then
    echo "remote_path: ${REMOTE_PATH}"
  fi
  if [[ -n "${HEALTH_URL}" ]]; then
    echo "health_url: ${HEALTH_URL}"
  fi
  if [[ -n "${EXCLUDE_FILE}" ]]; then
    echo "exclude_file: ${EXCLUDE_FILE}"
  fi
} > "${DEFAULTS}"
chmod 600 "${DEFAULTS}"

echo "ssh-remote: wrote ${DEFAULTS}"
cat "${DEFAULTS}"
